name: 'Project Assigner'
description: 'Assigns an issue to a project based on its label at the time it is opened or labeled'
inputs:
  issue-mappings:
    description: 'A JSON array of objects containing label, projectNumber, columnName and optional projectScope attributes.'
    required: true
  ghToken:
    description: 'A GitHub token with write access to the destination project and read access to the source issue. See https://docs.github.com/en/actions/reference/encrypted-secrets'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
