name: Import detect-secrets baseline from repo

on: 
  workflow_dispatch:
    inputs:
      baselineFile:
        description: 'GitHub path of the existing detect-secret baseline file'     
        required: true
        default: 'detect-secrets-sarif/test_data_repo/detect-secrets.json'

jobs:
  run:
    runs-on: ubuntu-latest
    name: A job to push detect-secrets baseline findings to GitHub
    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Convert detect-secrets findings to sarif format 
      id: sarif-convert
      uses: ./detect-secrets-sarif
      with:
        baseline-file-path: ${{ github.event.inputs.baselineFile }}  
      env:
        MGH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Sarif to GitHub
      uses: github/codeql-action/upload-sarif@v1 
      with:
        sarif_file: ${{ steps.sarif-convert.outputs.sarif-file-path }}
        token: ${{ secrets.GITHUB_TOKEN }}  
