on: 
  pull_request:
    types: [ready_for_review]

jobs:
  secrets_detector_job:
    runs-on: ubuntu-latest
    name: A job to push detect-secrets findings to GitHub
    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: push 
      id: push
      uses: ./secrets-detector
      with:
        baseline-file-path: "./secrets-detectors/test_data/baseline.file"
      env:  
        MGH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Get the output HTTP response code
      run: echo "The HTTP response code was ${{ steps.push.outputs.http-response-code }}"
