name: secrets-detector

on: 
  pull_request:
    branches: [ main ]

jobs:
  secrets_detector_job:
    runs-on: ubuntu-latest
    name: A job to push detect-secrets findings to GitHub
    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Convert detect-secrets findings to sarif format 
      id: sarif-convert
      uses: ./secrets-detector
      with:
        baseline-file-path: "secrets-detector/test_data/detect-secrets.json"
        sarif-file-path: "secrets-detector/test_data/detect-secrets.sarif.json"
      env:  
        MGH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
